window.SUPABASE_URL = "https://whoecasgekueqasatjuh.supabase.co";
window.SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indob2VjYXNnZWt1ZXFhc2F0anVoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODEwMjAxNzQsImV4cCI6MjA5NjU5NjE3NH0.lZgXLuQFjfdsAMYWmjkScPhMDXrSQvgFfq0ntGP3K_Q";
